import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico?v=1",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        {/* Contact Bar */}
        <div className="py-3 px-6" style={{ backgroundColor: "#f5f1e8" }}>
          <div className="max-w-6xl mx-auto flex justify-center items-center gap-6 text-sm md:text-base">
            <a href="tel:+2066197551" className="hover:text-blue-400 transition flex items-center gap-2" style={{ color: "#2d3a6b" }}>
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
              </svg>
              (206) 619-7551
            </a>
            <a href="mailto:markpyvovarov@gmail.com" className="hover:text-blue-400 transition flex items-center gap-2" style={{ color: "#2d3a6b" }}>
              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
              markpyvovarov@gmail.com
            </a>
          </div>
        </div>

        {/* Navigation Bar */}
        <nav className="shadow-sm sticky top-0 z-50" style={{ backgroundColor: "#2d3a6b" }}>
          <div className="max-w-6xl mx-auto px-6 py-4 flex items-center">
            <Image
              src="/logonotext.png"
              alt="PressureWash Logo"
              width={60}
              height={60}
              className="h-auto w-auto flex-shrink-0"
            />
            <div className="flex gap-8 items-center flex-1 justify-center">
              <a href="/" className="text-white hover:text-blue-300 transition font-bold text-lg">
                Home
              </a>
              <div className="relative group">
                <button className="text-white hover:text-blue-300 transition font-bold flex items-center gap-1 text-lg">
                  Services
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 9l6 6 6-6" />
                  </svg>
                </button>
                <div className="absolute left-0 mt-0 w-48 bg-white text-gray-800 rounded-lg shadow-lg opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200 py-2 z-10">
                  <a href="/house-washing" className="block px-4 py-2 hover:bg-gray-100 transition font-semibold">
                    House Washing
                  </a>
                  <a href="/pressure-washing" className="block px-4 py-2 hover:bg-gray-100 transition font-semibold">
                    Pressure Washing
                  </a>
                  <a href="/window-cleaning" className="block px-4 py-2 hover:bg-gray-100 transition font-semibold">
                    Window Cleaning
                  </a>
                </div>
              </div>
              <a href="/gallery" className="text-white hover:text-blue-300 transition font-bold text-lg">
                Gallery
              </a>
              <a href="#about" className="text-white hover:text-blue-300 transition font-bold text-lg">
                About
              </a>
              <a href="/quote" className="text-white hover:text-blue-300 transition font-bold text-lg">
                Contact
              </a>
            </div>
          </div>
        </nav>

        {children}

        {/* Footer */}
        <footer className="mt-20" style={{ backgroundColor: "#2d3a6b" }}>
          <div className="max-w-6xl mx-auto px-6 py-12">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-white mb-8">
              {/* Contact Section */}
              <div>
                <h3 className="text-xl font-bold mb-4">Contact Us</h3>
                <div className="space-y-2">
                  <p className="flex items-center gap-2">
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" />
                    </svg>
                    (206) 619-7551
                  </p>
                  <p className="flex items-center gap-2">
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                    </svg>
                    markpyvovarov@gmail.com
                  </p>
                  <div className="flex gap-4 mt-4 pt-4">
                    <a href="https://www.instagram.com/waterboyslangley?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 hover:text-blue-300 transition">
                      <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                        <path d="M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849 0 3.205-.012 3.584-.069 4.849-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07-3.204 0-3.584-.012-4.849-.07-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849 0-3.204.013-3.583.07-4.849.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zm0-2.163c-3.259 0-3.667.014-4.947.072-4.358.2-6.78 2.618-6.98 6.98-.059 1.281-.073 1.689-.073 4.948 0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98-1.281-.059-1.69-.073-4.949-.073zM5.838 12a6.162 6.162 0 1 1 12.324 0 6.162 6.162 0 0 1-12.324 0zM12 16a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm4.965-10.322a1.44 1.44 0 1 1 2.881.001 1.44 1.44 0 0 1-2.881-.001z" />
                      </svg>
                      Instagram
                    </a>
                    <a href="https://www.linkedin.com/company/water-boys-pressure-washing" target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 hover:text-blue-300 transition">
                      <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                        <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.225 0z" />
                      </svg>
                      LinkedIn
                    </a>
                  </div>
                </div>
              </div>

              {/* Services Links */}
              <div>
                <h3 className="text-xl font-bold mb-4">Services</h3>
                <ul className="space-y-2">
                  <li>
                    <a href="/house-washing" className="hover:text-blue-300 transition">
                      House Washing
                    </a>
                  </li>
                  <li>
                    <a href="/pressure-washing" className="hover:text-blue-300 transition">
                      Pressure Washing
                    </a>
                  </li>
                  <li>
                    <a href="/window-cleaning" className="hover:text-blue-300 transition">
                      Window Cleaning
                    </a>
                  </li>
                </ul>
              </div>

              {/* Quick Links */}
              <div>
                <h3 className="text-xl font-bold mb-4">Quick Links</h3>
                <ul className="space-y-2">
                  <li>
                    <a href="/" className="hover:text-blue-300 transition">
                      Home
                    </a>
                  </li>
                  <li>
                    <a href="/gallery" className="hover:text-blue-300 transition">
                      Gallery
                    </a>
                  </li>
                  <li>
                    <a href="/quote" className="hover:text-blue-300 transition">
                      Get a Quote
                    </a>
                  </li>
                </ul>
              </div>
            </div>

            {/* Footer Bottom */}
            <div className="border-t border-white border-opacity-20 pt-8 text-center text-white text-sm">
              <p>&copy; 2026 Water Boys Pressure Washing. All rights reserved.</p>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
